--- 
title: "Full Stack Data Science"
author: "Alexander Engelhardt"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: AlexEngelhardt/full-stack-data-science-book
description: "This is a book about the mythical Full Stack Data Scientist, and the tools, skills and topics that are important for a generalist in this field."
---

```{r echo=FALSE}
# setup code goes here
```

# Preface {-}

This is a book about the mythical Full Stack Data Scientist,
and the tools, skills and topics that are important for a generalist in this
field.

The focus are skills that are not pure machine learning but that you also need to deliver a full data product, for example building the software infrastructure, or making your final model public via an API.

## Goal of this book {-}

This book aims to teach at least awareness of all topics that are not the core ML skills you already learn at university or in a MOOC. Its goal is not to make you an expert in any of them, but to give you a birds-eye view of the whole landscape. Because if you don't know that screwdrivers exist, you'll use your hammer to drive in a screw. And if you know these topics exist, you can choose the appropriate tool for the job (even if you'll first have to learn it).

Also, knowing about adjacent fields like DevOps, even if you won't use it in your job, you will know common pitfalls and problems and will build better products to hand over to the operations team (i.e. your model will be easier for them to put into production).

## Target audience {-}

This book is aimed at

- The data science graduate (university or MOOC) who has some experience in building prediction models and wants to choose the most fitting field to specialize in.
- The expert in a particular field who wants to broaden his view and see how his skills fit into the bigger picture
- The consultant who needs to become a generalist to quickly adapt to each new client's existing environment
- The solo entrepreneur or startup founder who has no other choice than to build the entire data product himself
- The IT executive who oversees the full pipeline from infrastructure to final data products and who needs a broad awareness of all topics across the data value chain to make informed decisions

## Prior knowledge assumed {-}

This book does not start at zero. It assumes familiarity with some common Machine Learning algorithms, and basic programming skills. For example, you should be able to tune and train a Random Forest on a [credit data set](https://www.openml.org/d/31) to predict whether a loan application belongs to the "good" or "bad" class.

## Feedback {-}

I am happy for all kinds of feedback I can get on it. Especially helpful would be feedback on whether I forgot a specific topic, or if something is unnecessary and can be removed, or if the structure/organization of the contents can be improved.

For feedback you can send me an e-mail at alexander.w.engelhardt@gmail.com

## Acknowledgments {-}

I am very grateful to Christoph Molnar, Heidi Seibold, Janek Thomas and Alessandro Volpicella for reviewing early versions of the book's scope and contents.

In the research phase, I used a wide variety of sources, but I want to particularly mention the blog [*Letters to a new Developer*](https://letterstoanewdeveloper.com), because Dan's writing is incredibly valuable to every kind of IT professional.
